#! /usr/bin/env python

import argparse
import sys

from pooltool.ani.animate import Play


def main(args):
    play = Play(monitor=args.monitor)
    play.start()


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument(
        "--monitor", action="store_true", help="Spit out per-frame info about game"
    )
    args = ap.parse_args()

    main(args)
