#! /usr/bin/env python

import sys
import argparse

ap = argparse.ArgumentParser()
args = ap.parse_args()

if __name__ == '__main__':
    from pooltool.ani.animate import Play
    play = Play()
    play.start()
