from typing import Any

def get_next_event(*args: Any, **kwargs: Any) -> Any: ...
def get_next_ball_ball_collision(*args: Any, **kwargs: Any) -> Any: ...
def get_next_ball_circular_cushion_event(*args: Any, **kwargs: Any) -> Any: ...
def get_next_ball_linear_cushion_collision(*args: Any, **kwargs: Any) -> Any: ...
def get_next_ball_pocket_collision(*args: Any, **kwargs: Any) -> Any: ...
